package com.mycompany.projectmotos;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class CadEsportiva extends javax.swing.JFrame {
  
  private static CadEsportiva cadEsportivaUnic;
  private Esportiva e = new Esportiva();

  public CadEsportiva() {
    initComponents();
    this.setLocationRelativeTo(null);
  }
  
  public static CadEsportiva getCadEsportiva(){
    if(cadEsportivaUnic == null){
      cadEsportivaUnic = new CadEsportiva();
    }
    
    return cadEsportivaUnic;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel8 = new javax.swing.JLabel();
    lblCadastrodeMotoEsportiva = new javax.swing.JLabel();
    lblNome = new javax.swing.JLabel();
    tfNome = new javax.swing.JTextField();
    lblCpf = new javax.swing.JLabel();
    lblIdade = new javax.swing.JLabel();
    tfCpf = new javax.swing.JTextField();
    tfIdade = new javax.swing.JTextField();
    lblDadosPessoa = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();
    tfPlaca = new javax.swing.JTextField();
    tfMarca = new javax.swing.JTextField();
    tfModelo = new javax.swing.JTextField();
    tfCor = new javax.swing.JTextField();
    lblPlaca = new javax.swing.JLabel();
    lblMarca = new javax.swing.JLabel();
    lblModelo = new javax.swing.JLabel();
    lblCor = new javax.swing.JLabel();
    lblPeso = new javax.swing.JLabel();
    lblValor = new javax.swing.JLabel();
    lblCilindrada = new javax.swing.JLabel();
    lblDadosEspecificosMoto = new javax.swing.JLabel();
    tfPeso = new javax.swing.JTextField();
    tfValor = new javax.swing.JTextField();
    tfCilindrada = new javax.swing.JTextField();
    tfSistemadeFreio = new javax.swing.JTextField();
    lblSistemadeFreio = new javax.swing.JLabel();
    lblVelocidade = new javax.swing.JLabel();
    lblChassi = new javax.swing.JLabel();
    tfVelocidade = new javax.swing.JTextField();
    tfChassi = new javax.swing.JTextField();
    lblFreioDisco = new javax.swing.JLabel();
    lblFreioAbs = new javax.swing.JLabel();
    lblFreioTambor = new javax.swing.JLabel();
    lblChassiTrelica = new javax.swing.JLabel();
    lblChassiAluminio = new javax.swing.JLabel();
    lblChassiFibra = new javax.swing.JLabel();
    lblChassiDupla = new javax.swing.JLabel();
    btnInserir = new javax.swing.JButton();
    btnConsultar = new javax.swing.JButton();
    btnAlterar = new javax.swing.JButton();
    btnExcluir = new javax.swing.JButton();
    btnLimpar = new javax.swing.JButton();
    btnSair = new javax.swing.JButton();
    mbMenu = new javax.swing.JMenuBar();
    mbEsportiva = new javax.swing.JMenu();
    miRelatorioGeral = new javax.swing.JMenuItem();
    mbTouring = new javax.swing.JMenu();
    miCadTouring = new javax.swing.JMenuItem();
    miRelatorio = new javax.swing.JMenuItem();
    mbOffroad = new javax.swing.JMenu();
    miCadOffroad = new javax.swing.JMenuItem();
    miRegistroGera = new javax.swing.JMenuItem();
    mbVoltar = new javax.swing.JMenu();
    miMenuInicial = new javax.swing.JMenuItem();

    jLabel8.setText("jLabel8");

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    lblCadastrodeMotoEsportiva.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
    lblCadastrodeMotoEsportiva.setText("Cadastro de Moto Esportiva");

    lblNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    lblNome.setText("Nome:");

    tfNome.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        tfNomeActionPerformed(evt);
      }
    });

    lblCpf.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    lblCpf.setText("Cpf:");

    lblIdade.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    lblIdade.setText("Idade:");

    lblDadosPessoa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    lblDadosPessoa.setText("Dados Pessoa");

    jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    jLabel1.setText("Dados Gerais Moto");

    lblPlaca.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    lblPlaca.setText("Placa:");

    lblMarca.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    lblMarca.setText("Marca:");

    lblModelo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    lblModelo.setText("Modelo:");

    lblCor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    lblCor.setText("Cor:");

    lblPeso.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    lblPeso.setText("Peso:");

    lblValor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    lblValor.setText("Valor:");

    lblCilindrada.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    lblCilindrada.setText("Cilindrada:");

    lblDadosEspecificosMoto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    lblDadosEspecificosMoto.setText("Dados Especificos Moto");

    tfSistemadeFreio.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        tfSistemadeFreioActionPerformed(evt);
      }
    });

    lblSistemadeFreio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    lblSistemadeFreio.setText("Sistema de freio:");

    lblVelocidade.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    lblVelocidade.setText("Velocidade de 0 à 100:");

    lblChassi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    lblChassi.setText("Chassi:");

    lblFreioDisco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    lblFreioDisco.setText("1 - Disco");

    lblFreioAbs.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    lblFreioAbs.setText("2 - ABS");

    lblFreioTambor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    lblFreioTambor.setText("3 - Tambor");

    lblChassiTrelica.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    lblChassiTrelica.setText("1 - Trelica");

    lblChassiAluminio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    lblChassiAluminio.setText("2 - Aluminio");

    lblChassiFibra.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    lblChassiFibra.setText("3 - Fibra de Carbono");

    lblChassiDupla.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    lblChassiDupla.setText("4 - Dupla Trave");

    btnInserir.setText("Inserir");
    btnInserir.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnInserirActionPerformed(evt);
      }
    });

    btnConsultar.setText("Consultar");
    btnConsultar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnConsultarActionPerformed(evt);
      }
    });

    btnAlterar.setText("Alterar");
    btnAlterar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnAlterarActionPerformed(evt);
      }
    });

    btnExcluir.setText("Excluir");
    btnExcluir.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnExcluirActionPerformed(evt);
      }
    });

    btnLimpar.setText("Limpar");
    btnLimpar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnLimparActionPerformed(evt);
      }
    });

    btnSair.setText("Sair");
    btnSair.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSairActionPerformed(evt);
      }
    });

    mbEsportiva.setText("Esportiva");

    miRelatorioGeral.setText("Relatorio Geral...");
    miRelatorioGeral.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        miRelatorioGeralActionPerformed(evt);
      }
    });
    mbEsportiva.add(miRelatorioGeral);

    mbMenu.add(mbEsportiva);

    mbTouring.setText("Touring");

    miCadTouring.setText("Cadastro...");
    miCadTouring.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        miCadTouringActionPerformed(evt);
      }
    });
    mbTouring.add(miCadTouring);

    miRelatorio.setText("Registro Geral...");
    miRelatorio.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        miRelatorioActionPerformed(evt);
      }
    });
    mbTouring.add(miRelatorio);

    mbMenu.add(mbTouring);

    mbOffroad.setText("Offroad");

    miCadOffroad.setText("Cadastro...");
    miCadOffroad.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        miCadOffroadActionPerformed(evt);
      }
    });
    mbOffroad.add(miCadOffroad);

    miRegistroGera.setText("Registro Geral...");
    miRegistroGera.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        miRegistroGeraActionPerformed(evt);
      }
    });
    mbOffroad.add(miRegistroGera);

    mbMenu.add(mbOffroad);

    mbVoltar.setText("Voltar");

    miMenuInicial.setText("Menu Inicial...");
    miMenuInicial.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        miMenuInicialActionPerformed(evt);
      }
    });
    mbVoltar.add(miMenuInicial);

    mbMenu.add(mbVoltar);

    setJMenuBar(mbMenu);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addComponent(lblCpf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(layout.createSequentialGroup()
                .addComponent(lblNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addComponent(lblDadosPessoa)
              .addGroup(layout.createSequentialGroup()
                .addComponent(lblIdade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addComponent(jLabel1)
              .addGroup(layout.createSequentialGroup()
                .addComponent(lblPlaca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(layout.createSequentialGroup()
                .addComponent(lblMarca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(layout.createSequentialGroup()
                .addComponent(lblModelo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(layout.createSequentialGroup()
                .addComponent(lblCor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfCor, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(layout.createSequentialGroup()
                .addComponent(lblPeso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(layout.createSequentialGroup()
                .addComponent(lblValor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfValor, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(layout.createSequentialGroup()
                .addComponent(lblCilindrada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfCilindrada, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addComponent(lblDadosEspecificosMoto)
              .addGroup(layout.createSequentialGroup()
                .addComponent(lblSistemadeFreio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfSistemadeFreio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(lblFreioAbs)
                  .addComponent(lblFreioDisco)
                  .addComponent(lblFreioTambor)))
              .addGroup(layout.createSequentialGroup()
                .addComponent(lblVelocidade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfVelocidade, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(layout.createSequentialGroup()
                .addComponent(lblChassi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfChassi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addComponent(lblChassiTrelica)
              .addComponent(lblChassiAluminio)
              .addComponent(lblChassiFibra)
              .addComponent(lblChassiDupla)))
          .addGroup(layout.createSequentialGroup()
            .addGap(59, 59, 59)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(btnInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(28, 28, 28)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
          .addGroup(layout.createSequentialGroup()
            .addGap(58, 58, 58)
            .addComponent(lblCadastrodeMotoEsportiva)))
        .addContainerGap(50, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(18, 18, 18)
        .addComponent(lblCadastrodeMotoEsportiva)
        .addGap(18, 18, 18)
        .addComponent(lblDadosPessoa)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblNome)
          .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblCpf)
          .addComponent(tfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblIdade)
          .addComponent(tfIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addComponent(jLabel1)
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblPlaca)
          .addComponent(tfPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblMarca)
          .addComponent(tfMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblModelo)
          .addComponent(tfModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblCor)
          .addComponent(tfCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblPeso)
          .addComponent(tfPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblValor)
          .addComponent(tfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblCilindrada)
          .addComponent(tfCilindrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addComponent(lblDadosEspecificosMoto)
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblSistemadeFreio)
          .addComponent(tfSistemadeFreio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(lblFreioDisco)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(lblFreioAbs)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(lblFreioTambor)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblVelocidade)
          .addComponent(tfVelocidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblChassi)
          .addComponent(tfChassi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(lblChassiTrelica)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(lblChassiAluminio)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(lblChassiFibra)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(lblChassiDupla)
        .addGap(29, 29, 29)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnInserir)
          .addComponent(btnAlterar)
          .addComponent(btnLimpar))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnConsultar)
          .addComponent(btnExcluir)
          .addComponent(btnSair))
        .addContainerGap(35, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void tfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_tfNomeActionPerformed

  private void tfSistemadeFreioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSistemadeFreioActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_tfSistemadeFreioActionPerformed

  private void miRelatorioGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRelatorioGeralActionPerformed
    RelatorioGeralEsportiva.getRelGerEsportiva().setVisible(true);
    this.dispose();
  }//GEN-LAST:event_miRelatorioGeralActionPerformed

  private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
    try {
      cadEsportiva();
      limpar();
    } catch (CpfPeqException ex) {
      Logger.getLogger(CadTouring.class.getName()).log(Level.SEVERE, null, ex);
    } catch (CpfGrdException ex) {
      Logger.getLogger(CadTouring.class.getName()).log(Level.SEVERE, null, ex);
    } catch (IdadeGrdException ex) {
      Logger.getLogger(CadTouring.class.getName()).log(Level.SEVERE, null, ex);
    } catch (IdadePeqException ex) {
      Logger.getLogger(CadTouring.class.getName()).log(Level.SEVERE, null, ex);
    }
  }//GEN-LAST:event_btnInserirActionPerformed

  private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
    altEsportiva();
    limpar();
  }//GEN-LAST:event_btnAlterarActionPerformed

  private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
    limpar();
  }//GEN-LAST:event_btnLimparActionPerformed

  private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
    consEsportiva();
  }//GEN-LAST:event_btnConsultarActionPerformed

  private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
    excluirEsportiva();
    limpar();
  }//GEN-LAST:event_btnExcluirActionPerformed

  private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
    sair();
  }//GEN-LAST:event_btnSairActionPerformed

  private void miCadTouringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadTouringActionPerformed
    CadTouring.getCadTouring().setVisible(true);
    this.dispose();
  }//GEN-LAST:event_miCadTouringActionPerformed

  private void miRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRelatorioActionPerformed
    RelatorioGeralTouring.getRelGerTouring().setVisible(true);
    this.dispose();
  }//GEN-LAST:event_miRelatorioActionPerformed

  private void miCadOffroadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadOffroadActionPerformed
    CadOffroad.getCadOffroad().setVisible(true);
    this.dispose();
  }//GEN-LAST:event_miCadOffroadActionPerformed

  private void miRegistroGeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRegistroGeraActionPerformed
    RelatorioGeralOffroad.getRelGerOffroad().setVisible(true);
    this.dispose();
  }//GEN-LAST:event_miRegistroGeraActionPerformed

  private void miMenuInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miMenuInicialActionPerformed
    TelaInicial.getTelaInicial().setVisible(true);
    this.dispose();
  }//GEN-LAST:event_miMenuInicialActionPerformed

  public void limpar(){
    tfPlaca.setText("");
    tfSistemadeFreio.setText("");
    tfCilindrada.setText("");
    tfChassi.setText("");
    tfCor.setText("");
    tfCpf.setText("");
    tfIdade.setText("");
    tfVelocidade.setText("");
    tfMarca.setText("");
    tfModelo.setText("");
    tfNome.setText("");
    tfPeso.setText("");
    tfValor.setText("");
  }
  
  public void sair(){
        int resp = JOptionPane.showConfirmDialog(null, "Deseja sair?", "Saída", JOptionPane.YES_NO_OPTION);
        
        if(resp == 0){
            System.exit(0);
        }
    }
  
  public void cadEsportiva() throws CpfPeqException, CpfGrdException, IdadeGrdException, IdadePeqException{
    try{
      e = new Esportiva();
      
      e.setPlaca(tfPlaca.getText());
      e.setVelocidade_zero_cem(Integer.parseInt(tfVelocidade.getText()));
      e.setCilindradas(Integer.parseInt(tfCilindrada.getText()));
      e.setChassi(tfChassi.getText());
      e.setCor(tfCor.getText());
      e.setCpf(Integer.parseInt(tfCpf.getText()));
      e.setIdade(Integer.parseInt(tfIdade.getText()));
      e.setSistema_freio(tfSistemadeFreio.getText());
      e.setMarca(tfMarca.getText());
      e.setModelo(tfModelo.getText());
      e.setNome(tfNome.getText());
      e.setPeso(Integer.parseInt(tfPeso.getText()));
      e.setValor(Integer.parseInt(tfValor.getText()));
      
      e = Banco.getBancoMotors().cadEsportiva(e);
      
      if(e != null){
        JOptionPane.showMessageDialog(null, "Moto Cadastrada!", "Aviso", 1);
      }
      else{
        JOptionPane.showMessageDialog(null, "Moto ja cadastrada!", "Aviso", 0);
      }
      
    }
    catch(NumberFormatException e) {
      JOptionPane.showMessageDialog(null, "+Capacidade do tanque\n+Cilindradas\n+CPF\n+Idade\n+Peso\n+Valor\ndevem ser valores inteiros", "ATENCAO",2);
      limpar();
    }
  }
  
  public void consEsportiva(){
    e = new Esportiva();
    e.setPlaca(tfPlaca.getText());
    e = Banco.getBancoMotors().consEsportiva(e);
    
    if(e != null){
      tfPlaca.setText(e.getPlaca());
      tfVelocidade.setText(Integer.toString((int) e.getVelocidade_zero_cem()));
      tfCilindrada.setText(Integer.toString(e.getCilindradas()));
      tfChassi.setText(e.getChassi());
      tfCor.setText(e.getCor());
      tfCpf.setText(Integer.toString(e.getCpf()));
      tfIdade.setText(Integer.toString(e.getIdade()));
      tfSistemadeFreio.setText(e.getSistema_freio());
      tfMarca.setText(e.getMarca());
      tfModelo.setText(e.getModelo());
      tfNome.setText(e.getNome());
      tfPeso.setText(Integer.toString((int) e.getPeso()));
      tfValor.setText(Integer.toString((int) e.getValor()));
    }
    else{
      JOptionPane.showMessageDialog(null,"CPF nao cadastrado", "Consulta de Moto",0);
    }
  }
  
  public void excluirEsportiva(){
    e = new Esportiva();
    e.setPlaca(tfPlaca.getText());
    e = Banco.getBancoMotors().deletarEsportiva(e);
    
    if(e != null){
            JOptionPane.showMessageDialog(null, "Moto excluída com sucesso!", "Exclusão de Moto", 1);
        }else{
            JOptionPane.showMessageDialog(null, "Placa não cadastrada", "Exclusão de Moto", 0);
        }
    
  }
  
  public void altEsportiva(){
    try{
      e = new Esportiva();
      e.setPlaca(tfPlaca.getText());
      e = Banco.getBancoMotors().alterarEsportiva(e);
      
      if(e != null){
        tfPlaca.setText(e.getPlaca());
        tfVelocidade.setText(Integer.toString((int) e.getVelocidade_zero_cem()));
        tfCilindrada.setText(Integer.toString(e.getCilindradas()));
        tfChassi.setText(e.getChassi());
        tfCor.setText(e.getCor());
        tfCpf.setText(Integer.toString(e.getCpf()));
        tfIdade.setText(Integer.toString(e.getIdade()));
        tfSistemadeFreio.setText(e.getSistema_freio());
        tfMarca.setText(e.getMarca());
        tfModelo.setText(e.getModelo());
        tfNome.setText(e.getNome());
        tfPeso.setText(Integer.toString((int) e.getPeso()));
        tfValor.setText(Integer.toString((int) e.getValor()));
      }
      else{
        JOptionPane.showMessageDialog(null, "Placa não cadastrada", "Alteração de Moto", 0);
      } 
    }
    catch(NumberFormatException e){
      JOptionPane.showMessageDialog(null, "+Capacidade do Tanque\n+Cilindrada\n+Cpf\n+Idade\n+Peso\n+Valor\ndevem ser números inteiros", "ATENÇÃO", 2);
      limpar();
    }
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnAlterar;
  private javax.swing.JButton btnConsultar;
  private javax.swing.JButton btnExcluir;
  private javax.swing.JButton btnInserir;
  private javax.swing.JButton btnLimpar;
  private javax.swing.JButton btnSair;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel lblCadastrodeMotoEsportiva;
  private javax.swing.JLabel lblChassi;
  private javax.swing.JLabel lblChassiAluminio;
  private javax.swing.JLabel lblChassiDupla;
  private javax.swing.JLabel lblChassiFibra;
  private javax.swing.JLabel lblChassiTrelica;
  private javax.swing.JLabel lblCilindrada;
  private javax.swing.JLabel lblCor;
  private javax.swing.JLabel lblCpf;
  private javax.swing.JLabel lblDadosEspecificosMoto;
  private javax.swing.JLabel lblDadosPessoa;
  private javax.swing.JLabel lblFreioAbs;
  private javax.swing.JLabel lblFreioDisco;
  private javax.swing.JLabel lblFreioTambor;
  private javax.swing.JLabel lblIdade;
  private javax.swing.JLabel lblMarca;
  private javax.swing.JLabel lblModelo;
  private javax.swing.JLabel lblNome;
  private javax.swing.JLabel lblPeso;
  private javax.swing.JLabel lblPlaca;
  private javax.swing.JLabel lblSistemadeFreio;
  private javax.swing.JLabel lblValor;
  private javax.swing.JLabel lblVelocidade;
  private javax.swing.JMenu mbEsportiva;
  private javax.swing.JMenuBar mbMenu;
  private javax.swing.JMenu mbOffroad;
  private javax.swing.JMenu mbTouring;
  private javax.swing.JMenu mbVoltar;
  private javax.swing.JMenuItem miCadOffroad;
  private javax.swing.JMenuItem miCadTouring;
  private javax.swing.JMenuItem miMenuInicial;
  private javax.swing.JMenuItem miRegistroGera;
  private javax.swing.JMenuItem miRelatorio;
  private javax.swing.JMenuItem miRelatorioGeral;
  private javax.swing.JTextField tfChassi;
  private javax.swing.JTextField tfCilindrada;
  private javax.swing.JTextField tfCor;
  private javax.swing.JTextField tfCpf;
  private javax.swing.JTextField tfIdade;
  private javax.swing.JTextField tfMarca;
  private javax.swing.JTextField tfModelo;
  private javax.swing.JTextField tfNome;
  private javax.swing.JTextField tfPeso;
  private javax.swing.JTextField tfPlaca;
  private javax.swing.JTextField tfSistemadeFreio;
  private javax.swing.JTextField tfValor;
  private javax.swing.JTextField tfVelocidade;
  // End of variables declaration//GEN-END:variables
}
