//ALLAN VINICIOOS FERRAZ SANTOS 2465272
package com.mycompany.projectmotos;

import javax.swing.JOptionPane;

public class CadOffroad extends javax.swing.JFrame {

  private static CadOffroad cadOffroadUnico;
  private Offroad o = new Offroad();
  
  public CadOffroad() {
    initComponents();
    this.setLocationRelativeTo(null);
  }
  
  public static CadOffroad getCadOffroad(){
    if(cadOffroadUnico == null){
        cadOffroadUnico = new CadOffroad();
    }
    return cadOffroadUnico;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    tfCpf = new javax.swing.JTextField();
    lblCilindrada = new javax.swing.JLabel();
    tfPlaca = new javax.swing.JTextField();
    lblDadosEspecificosMoto = new javax.swing.JLabel();
    tfMarca = new javax.swing.JTextField();
    tfPeso = new javax.swing.JTextField();
    tfModelo = new javax.swing.JTextField();
    lblCadastrodeMotoOffroad = new javax.swing.JLabel();
    tfCor = new javax.swing.JTextField();
    tfValor = new javax.swing.JTextField();
    lblPlaca = new javax.swing.JLabel();
    lblNome = new javax.swing.JLabel();
    lblMarca = new javax.swing.JLabel();
    tfCilindrada = new javax.swing.JTextField();
    lblModelo = new javax.swing.JLabel();
    tfNome = new javax.swing.JTextField();
    lblCor = new javax.swing.JLabel();
    lblCpf = new javax.swing.JLabel();
    tfIdade = new javax.swing.JTextField();
    lblPeso = new javax.swing.JLabel();
    lblIdade = new javax.swing.JLabel();
    lblDadosPessoa = new javax.swing.JLabel();
    lblValor = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();
    tfProtecao = new javax.swing.JTextField();
    lblAltura = new javax.swing.JLabel();
    lblPneu = new javax.swing.JLabel();
    lblProtecao = new javax.swing.JLabel();
    tfAltura = new javax.swing.JTextField();
    lblPneuUm = new javax.swing.JLabel();
    lblPneuDois = new javax.swing.JLabel();
    lblPneuTres = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    tfPneu = new javax.swing.JTextField();
    lblPneuQuatro = new javax.swing.JLabel();
    lblPneuCinco = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    btnInserir = new javax.swing.JButton();
    btnConsultar = new javax.swing.JButton();
    btnAlterar = new javax.swing.JButton();
    btnExcluir = new javax.swing.JButton();
    btnLimpar = new javax.swing.JButton();
    btnSair = new javax.swing.JButton();
    mbMenu = new javax.swing.JMenuBar();
    mbEsportiva = new javax.swing.JMenu();
    miCadEsportiva = new javax.swing.JMenuItem();
    miRelatorioGeral = new javax.swing.JMenuItem();
    mbTouring = new javax.swing.JMenu();
    miCadTouring = new javax.swing.JMenuItem();
    miRelatorio = new javax.swing.JMenuItem();
    mbOffroad = new javax.swing.JMenu();
    miRegistroGera = new javax.swing.JMenuItem();
    mbVoltar = new javax.swing.JMenu();
    miMenuInicial = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    lblCilindrada.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    lblCilindrada.setText("Cilindrada:");

    lblDadosEspecificosMoto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    lblDadosEspecificosMoto.setText("Dados Especificos Moto");

    lblCadastrodeMotoOffroad.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
    lblCadastrodeMotoOffroad.setText("Cadastro de Moto Off-Road");

    lblPlaca.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    lblPlaca.setText("Placa:");

    lblNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    lblNome.setText("Nome:");

    lblMarca.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    lblMarca.setText("Marca:");

    lblModelo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    lblModelo.setText("Modelo:");

    tfNome.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        tfNomeActionPerformed(evt);
      }
    });

    lblCor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    lblCor.setText("Cor:");

    lblCpf.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    lblCpf.setText("Cpf:");

    lblPeso.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    lblPeso.setText("Peso:");

    lblIdade.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    lblIdade.setText("Idade:");

    lblDadosPessoa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    lblDadosPessoa.setText("Dados Pessoa");

    lblValor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    lblValor.setText("Valor:");

    jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    jLabel1.setText("Dados Gerais Moto");

    lblAltura.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    lblAltura.setText("Altura Minima do Solo:");

    lblPneu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    lblPneu.setText("Tipo de Pneu:");

    lblProtecao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    lblProtecao.setText("Protecao");

    lblPneuUm.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    lblPneuUm.setText("1 - Cravos ou Pinos");

    lblPneuDois.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    lblPneuDois.setText("2 - Cravos Intermediarios");

    lblPneuTres.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    lblPneuTres.setText("3 - Banda de Rodagem Escalonada");

    jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel2.setText("1 - Protetores de mao");

    jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel4.setText("2 - Protetor de Radiador");

    jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel5.setText("3 - Protetor de Motor");

    lblPneuQuatro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    lblPneuQuatro.setText("4 - Banda de Rodagem para Terreno Misto");

    lblPneuCinco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    lblPneuCinco.setText("5 - Banda de Rodagem Para Enduro");

    jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel6.setText("4 - Protetor Quadro");

    jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel7.setText("5 - Todas as Anteriores");

    btnInserir.setText("Inserir");

    btnConsultar.setText("Consultar");

    btnAlterar.setText("Alterar");

    btnExcluir.setText("Excluir");

    btnLimpar.setText("Limpar");

    btnSair.setText("Sair");

    mbEsportiva.setText("Esportiva");

    miCadEsportiva.setText("Cadastro...");
    miCadEsportiva.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        miCadEsportivaActionPerformed(evt);
      }
    });
    mbEsportiva.add(miCadEsportiva);

    miRelatorioGeral.setText("Relatorio Geral...");
    miRelatorioGeral.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        miRelatorioGeralActionPerformed(evt);
      }
    });
    mbEsportiva.add(miRelatorioGeral);

    mbMenu.add(mbEsportiva);

    mbTouring.setText("Touring");

    miCadTouring.setText("Cadastro...");
    miCadTouring.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        miCadTouringActionPerformed(evt);
      }
    });
    mbTouring.add(miCadTouring);

    miRelatorio.setText("Registro Geral...");
    miRelatorio.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        miRelatorioActionPerformed(evt);
      }
    });
    mbTouring.add(miRelatorio);

    mbMenu.add(mbTouring);

    mbOffroad.setText("Offroad");

    miRegistroGera.setText("Registro Geral...");
    miRegistroGera.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        miRegistroGeraActionPerformed(evt);
      }
    });
    mbOffroad.add(miRegistroGera);

    mbMenu.add(mbOffroad);

    mbVoltar.setText("Voltar");

    miMenuInicial.setText("Menu Inicial...");
    miMenuInicial.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        miMenuInicialActionPerformed(evt);
      }
    });
    mbVoltar.add(miMenuInicial);

    mbMenu.add(mbVoltar);

    setJMenuBar(mbMenu);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(lblCpf)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(tfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(lblNome)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(lblDadosPessoa)
          .addGroup(layout.createSequentialGroup()
            .addComponent(lblIdade)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(tfIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(jLabel1)
          .addGroup(layout.createSequentialGroup()
            .addComponent(lblPlaca)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(tfPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(lblMarca)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(tfMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(lblModelo)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(tfModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(lblCor)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(tfCor, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(lblPeso)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(tfPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(lblValor)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(tfValor, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(lblDadosEspecificosMoto)
          .addGroup(layout.createSequentialGroup()
            .addComponent(lblPneu)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(tfPneu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(lblAltura)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(tfAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addGap(6, 6, 6)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(lblPneuCinco)
              .addComponent(lblPneuDois)
              .addComponent(lblPneuUm)
              .addComponent(lblPneuTres)
              .addComponent(lblPneuQuatro)))
          .addGroup(layout.createSequentialGroup()
            .addComponent(lblProtecao)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(tfProtecao, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(jLabel4)
          .addComponent(jLabel2)
          .addComponent(jLabel5)
          .addComponent(jLabel6)
          .addComponent(jLabel7)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGap(28, 28, 28)
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                  .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(18, 18, 18)
                  .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                  .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(18, 18, 18)
                  .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(layout.createSequentialGroup()
              .addComponent(lblCilindrada)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
              .addComponent(tfCilindrada, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(lblCadastrodeMotoOffroad)))
        .addContainerGap(80, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(30, 30, 30)
        .addComponent(lblCadastrodeMotoOffroad)
        .addGap(18, 18, 18)
        .addComponent(lblDadosPessoa)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblNome)
          .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblCpf)
          .addComponent(tfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblIdade)
          .addComponent(tfIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addComponent(jLabel1)
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblPlaca)
          .addComponent(tfPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblMarca)
          .addComponent(tfMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblModelo)
          .addComponent(tfModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblCor)
          .addComponent(tfCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblPeso)
          .addComponent(tfPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblValor)
          .addComponent(tfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblCilindrada)
          .addComponent(tfCilindrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addComponent(lblDadosEspecificosMoto)
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblAltura)
          .addComponent(tfAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblPneu)
          .addComponent(tfPneu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(lblPneuUm)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(lblPneuDois)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(lblPneuTres)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(lblPneuQuatro)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(lblPneuCinco)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblProtecao)
          .addComponent(tfProtecao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel2)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel4)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel5)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel6)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel7)
        .addGap(27, 27, 27)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnInserir)
          .addComponent(btnAlterar)
          .addComponent(btnLimpar))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnConsultar)
          .addComponent(btnExcluir)
          .addComponent(btnSair))
        .addContainerGap(34, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void tfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_tfNomeActionPerformed

  private void miRelatorioGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRelatorioGeralActionPerformed
    RelatorioGeralEsportiva.getRelGerEsportiva().setVisible(true);
    this.dispose();
  }//GEN-LAST:event_miRelatorioGeralActionPerformed

  private void miCadEsportivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadEsportivaActionPerformed
    CadEsportiva.getCadEsportiva().setVisible(true);
    this.dispose();
  }//GEN-LAST:event_miCadEsportivaActionPerformed

  private void miCadTouringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadTouringActionPerformed
    CadTouring.getCadTouring().setVisible(true);
    this.dispose();
  }//GEN-LAST:event_miCadTouringActionPerformed

  private void miRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRelatorioActionPerformed
    RelatorioGeralTouring.getRelGerTouring().setVisible(true);
    this.dispose();
  }//GEN-LAST:event_miRelatorioActionPerformed

  private void miRegistroGeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRegistroGeraActionPerformed
    RelatorioGeralOffroad.getRelGerOffroad().setVisible(true);
    this.dispose();
  }//GEN-LAST:event_miRegistroGeraActionPerformed

  private void miMenuInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miMenuInicialActionPerformed
    TelaInicial.getTelaInicial().setVisible(true);
    this.dispose();
  }//GEN-LAST:event_miMenuInicialActionPerformed

  public void limpar(){
    tfPlaca.setText("");
    tfProtecao.setText("");
    tfCilindrada.setText("");
    tfAltura.setText("");
    tfCor.setText("");
    tfCpf.setText("");
    tfIdade.setText("");
    tfPneu.setText("");
    tfMarca.setText("");
    tfModelo.setText("");
    tfNome.setText("");
    tfPeso.setText("");
    tfValor.setText("");
  }
  
  public void sair(){
        int resp = JOptionPane.showConfirmDialog(null, "Deseja sair?", "Saída", JOptionPane.YES_NO_OPTION);
        
        if(resp == 0){
            System.exit(0);
        }
    }
  
  public void cadOffroad() throws CpfPeqException, CpfGrdException, IdadeGrdException, IdadePeqException{
    try{
      o = new Offroad();
      
      o.setPlaca(tfPlaca.getText());
      o.setAltura_minima_solo(Integer.parseInt(tfAltura.getText()));
      o.setCilindradas(Integer.parseInt(tfCilindrada.getText()));
      o.setPneus(tfPneu.getText());
      o.setCor(tfCor.getText());
      o.setCpf(Integer.parseInt(tfCpf.getText()));
      o.setIdade(Integer.parseInt(tfIdade.getText()));
      o.setProtecao(tfProtecao.getText());
      o.setMarca(tfMarca.getText());
      o.setModelo(tfModelo.getText());
      o.setNome(tfNome.getText());
      o.setPeso(Integer.parseInt(tfPeso.getText()));
      o.setValor(Integer.parseInt(tfValor.getText()));
      
      o = Banco.getBancoMotors().cadOffroad(o);
      
      if(o != null){
        JOptionPane.showMessageDialog(null, "Moto Cadastrada!", "Aviso", 1);
      }
      else{
        JOptionPane.showMessageDialog(null, "Moto ja cadastrada!", "Aviso", 0);
      }
      
    }
    catch(NumberFormatException e) {
      JOptionPane.showMessageDialog(null, "+Capacidade do tanque\n+Cilindradas\n+CPF\n+Idade\n+Peso\n+Valor\ndevem ser valores inteiros", "ATENCAO",2);
      limpar();
    }
  }
  
  public void consOffroad(){
    o = new Offroad();
    o.setPlaca(tfPlaca.getText());
    o = Banco.getBancoMotors().consOffroad(o);
    
    if(o != null){
      tfPlaca.setText(o.getPlaca());
      tfAltura.setText(Integer.toString((int) o.getsAltura_minima_solo()));
      tfCilindrada.setText(Integer.toString(o.getCilindradas()));
      tfProtecao.setText(o.getsprotecao());
      tfCor.setText(o.getCor());
      tfCpf.setText(Integer.toString(o.getCpf()));
      tfIdade.setText(Integer.toString(o.getIdade()));
      tfPneu.setText(o.getsprotecao());
      tfMarca.setText(o.getMarca());
      tfModelo.setText(o.getModelo());
      tfNome.setText(o.getNome());
      tfPeso.setText(Integer.toString((int) o.getPeso()));
      tfValor.setText(Integer.toString((int) o.getValor()));
    }
    else{
      JOptionPane.showMessageDialog(null,"CPF nao cadastrado", "Consulta de Moto",0);
    }
  }
  
  public void excluirOffroad(){
    o = new Offroad();
    o.setPlaca(tfPlaca.getText());
    o = Banco.getBancoMotors().deletarOffroad(o);
    
    if(o != null){
            JOptionPane.showMessageDialog(null, "Moto excluída com sucesso!", "Exclusão de Moto", 1);
        }else{
            JOptionPane.showMessageDialog(null, "Placa não cadastrada", "Exclusão de Moto", 0);
        }
    
  }
  
  public void altOffroad(){
    try{
      o = new Offroad();
      o.setPlaca(tfPlaca.getText());
      o = Banco.getBancoMotors().alterarOffroad(o);
      
      if(o != null){
        tfPlaca.setText(o.getPlaca());
        tfAltura.setText(Integer.toString((int) o.getsAltura_minima_solo()));
        tfCilindrada.setText(Integer.toString(o.getCilindradas()));
        tfProtecao.setText(o.getsprotecao());
        tfCor.setText(o.getCor());
        tfCpf.setText(Integer.toString(o.getCpf()));
        tfIdade.setText(Integer.toString(o.getIdade()));
        tfPneu.setText(o.getsprotecao());
        tfMarca.setText(o.getMarca());
        tfModelo.setText(o.getModelo());
        tfNome.setText(o.getNome());
        tfPeso.setText(Integer.toString((int) o.getPeso()));
        tfValor.setText(Integer.toString((int) o.getValor()));
      }
      else{
        JOptionPane.showMessageDialog(null, "Placa não cadastrada", "Alteração de Moto", 0);
      } 
    }
    catch(NumberFormatException e){
      JOptionPane.showMessageDialog(null, "+Capacidade do Tanque\n+Cilindrada\n+Cpf\n+Idade\n+Peso\n+Valor\ndevem ser números inteiros", "ATENÇÃO", 2);
      limpar();
    }
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnAlterar;
  private javax.swing.JButton btnConsultar;
  private javax.swing.JButton btnExcluir;
  private javax.swing.JButton btnInserir;
  private javax.swing.JButton btnLimpar;
  private javax.swing.JButton btnSair;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel lblAltura;
  private javax.swing.JLabel lblCadastrodeMotoOffroad;
  private javax.swing.JLabel lblCilindrada;
  private javax.swing.JLabel lblCor;
  private javax.swing.JLabel lblCpf;
  private javax.swing.JLabel lblDadosEspecificosMoto;
  private javax.swing.JLabel lblDadosPessoa;
  private javax.swing.JLabel lblIdade;
  private javax.swing.JLabel lblMarca;
  private javax.swing.JLabel lblModelo;
  private javax.swing.JLabel lblNome;
  private javax.swing.JLabel lblPeso;
  private javax.swing.JLabel lblPlaca;
  private javax.swing.JLabel lblPneu;
  private javax.swing.JLabel lblPneuCinco;
  private javax.swing.JLabel lblPneuDois;
  private javax.swing.JLabel lblPneuQuatro;
  private javax.swing.JLabel lblPneuTres;
  private javax.swing.JLabel lblPneuUm;
  private javax.swing.JLabel lblProtecao;
  private javax.swing.JLabel lblValor;
  private javax.swing.JMenu mbEsportiva;
  private javax.swing.JMenuBar mbMenu;
  private javax.swing.JMenu mbOffroad;
  private javax.swing.JMenu mbTouring;
  private javax.swing.JMenu mbVoltar;
  private javax.swing.JMenuItem miCadEsportiva;
  private javax.swing.JMenuItem miCadTouring;
  private javax.swing.JMenuItem miMenuInicial;
  private javax.swing.JMenuItem miRegistroGera;
  private javax.swing.JMenuItem miRelatorio;
  private javax.swing.JMenuItem miRelatorioGeral;
  private javax.swing.JTextField tfAltura;
  private javax.swing.JTextField tfCilindrada;
  private javax.swing.JTextField tfCor;
  private javax.swing.JTextField tfCpf;
  private javax.swing.JTextField tfIdade;
  private javax.swing.JTextField tfMarca;
  private javax.swing.JTextField tfModelo;
  private javax.swing.JTextField tfNome;
  private javax.swing.JTextField tfPeso;
  private javax.swing.JTextField tfPlaca;
  private javax.swing.JTextField tfPneu;
  private javax.swing.JTextField tfProtecao;
  private javax.swing.JTextField tfValor;
  // End of variables declaration//GEN-END:variables
}
