//ALLAN VINICIOS FERRAZ SANTOS 2465272

package com.mycompany.projectmotos;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class RelatorioGeralEsportiva extends javax.swing.JFrame {

  private static RelatorioGeralEsportiva relGerEsportiva;
  
  public RelatorioGeralEsportiva() {
    initComponents();
    this.setLocationRelativeTo(null);
  }
  
  public static RelatorioGeralEsportiva getRelGerEsportiva(){
    if(relGerEsportiva == null){
      relGerEsportiva = new RelatorioGeralEsportiva();
    }
    return relGerEsportiva;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jMenuItem1 = new javax.swing.JMenuItem();
    lblTituloRelatorio = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    tbEsportiva = new javax.swing.JTable();
    jMenuBar1 = new javax.swing.JMenuBar();
    mbEsportiva = new javax.swing.JMenu();
    miCadEsportiva = new javax.swing.JMenuItem();
    mbTouring = new javax.swing.JMenu();
    miCadTouring = new javax.swing.JMenuItem();
    miRelatorio = new javax.swing.JMenuItem();
    mbOffroad = new javax.swing.JMenu();
    miCadOffroad = new javax.swing.JMenuItem();
    miRelatorioGera = new javax.swing.JMenuItem();
    mbVoltar = new javax.swing.JMenu();
    miMenuInicial = new javax.swing.JMenuItem();

    jMenuItem1.setText("jMenuItem1");

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowActivated(java.awt.event.WindowEvent evt) {
        formWindowActivated(evt);
      }
    });

    lblTituloRelatorio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    lblTituloRelatorio.setText("Relatorio Geral - Moto Esportiva");

    tbEsportiva.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null, null, null, null}
      },
      new String [] {
        "NOME", "CPF", "IDADE", "PLACA", "MARCA", "MODELO", "COR", "PESO", "VALOR", "CILINDRADA", "SIS FREIO", "ZERO A CEM", "CHASSI"
      }
    ));
    tbEsportiva.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        tbEsportivaMouseClicked(evt);
      }
    });
    jScrollPane1.setViewportView(tbEsportiva);

    mbEsportiva.setText("Esportiva");

    miCadEsportiva.setText("Cadastro...");
    miCadEsportiva.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        miCadEsportivaActionPerformed(evt);
      }
    });
    mbEsportiva.add(miCadEsportiva);

    jMenuBar1.add(mbEsportiva);

    mbTouring.setText("Touring");

    miCadTouring.setText("Cadastro...");
    miCadTouring.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        miCadTouringActionPerformed(evt);
      }
    });
    mbTouring.add(miCadTouring);

    miRelatorio.setText("Relatorio Geral...");
    miRelatorio.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        miRelatorioActionPerformed(evt);
      }
    });
    mbTouring.add(miRelatorio);

    jMenuBar1.add(mbTouring);

    mbOffroad.setText("Offroad");

    miCadOffroad.setText("Cadastro...");
    miCadOffroad.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        miCadOffroadActionPerformed(evt);
      }
    });
    mbOffroad.add(miCadOffroad);

    miRelatorioGera.setText("Relatorio Geral...");
    miRelatorioGera.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        miRelatorioGeraActionPerformed(evt);
      }
    });
    mbOffroad.add(miRelatorioGera);

    jMenuBar1.add(mbOffroad);

    mbVoltar.setText("Voltar");

    miMenuInicial.setText("Menu Inicial...");
    miMenuInicial.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        miMenuInicialActionPerformed(evt);
      }
    });
    mbVoltar.add(miMenuInicial);

    jMenuBar1.add(mbVoltar);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane1)
        .addContainerGap())
      .addGroup(layout.createSequentialGroup()
        .addGap(283, 283, 283)
        .addComponent(lblTituloRelatorio)
        .addContainerGap(292, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(lblTituloRelatorio)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(19, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void miCadEsportivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadEsportivaActionPerformed
    CadEsportiva.getCadEsportiva().setVisible(true);
    this.dispose();
  }//GEN-LAST:event_miCadEsportivaActionPerformed

  private void tbEsportivaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbEsportivaMouseClicked
    selectTab();
  }//GEN-LAST:event_tbEsportivaMouseClicked

  private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
    listarTab();
  }//GEN-LAST:event_formWindowActivated

  private void miCadTouringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadTouringActionPerformed
    CadTouring.getCadTouring().setVisible(true);
    this.dispose();
  }//GEN-LAST:event_miCadTouringActionPerformed

  private void miCadOffroadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadOffroadActionPerformed
    CadOffroad.getCadOffroad().setVisible(true);
    this.dispose();
  }//GEN-LAST:event_miCadOffroadActionPerformed

  private void miMenuInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miMenuInicialActionPerformed
   TelaInicial.getTelaInicial().setVisible(true);
   this.dispose();
  }//GEN-LAST:event_miMenuInicialActionPerformed

  private void miRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRelatorioActionPerformed
    RelatorioGeralTouring.getRelGerTouring().setVisible(true);
    this.dispose();
  }//GEN-LAST:event_miRelatorioActionPerformed

  private void miRelatorioGeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRelatorioGeraActionPerformed
    RelatorioGeralOffroad.getRelGerOffroad().setVisible(true);
    this.dispose();
  }//GEN-LAST:event_miRelatorioGeraActionPerformed

  
  public void selectTab(){
    String valLin = "";
    int posLin = tbEsportiva.getSelectedRow();
    
    for(int col = 0; col < tbEsportiva.getComponentCount(); col++){
            valLin += tbEsportiva.getModel().getValueAt(posLin, col).toString();
            
            if(col+1 < tbEsportiva.getColumnCount()){
                valLin += " - ";
            }
        }
    JOptionPane.showMessageDialog(null, "Valor capturado: ", "Captura de Dados da Tabela", 1);
  }
  
  public void listarTab(){
        DefaultTableModel tabModel = (DefaultTableModel) tbEsportiva.getModel();
        int posLin = 0;
        tabModel.setRowCount(posLin);
        
        for(Esportiva e : Banco.getBancoMotors().getBdEsportiva()){
            tabModel.insertRow(posLin, new Object[]{e.getNome(), e.getCpf(), e.getIdade(), e.getPlaca(), e.getMarca(), e.getModelo(), e.getCor(), e.getPeso(), e.getValor(), e.getCilindradas(), e.getSistema_freio(), e.getVelocidade_zero_cem(), e.getChassi()});
            posLin++;
        }
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JMenuBar jMenuBar1;
  private javax.swing.JMenuItem jMenuItem1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JLabel lblTituloRelatorio;
  private javax.swing.JMenu mbEsportiva;
  private javax.swing.JMenu mbOffroad;
  private javax.swing.JMenu mbTouring;
  private javax.swing.JMenu mbVoltar;
  private javax.swing.JMenuItem miCadEsportiva;
  private javax.swing.JMenuItem miCadOffroad;
  private javax.swing.JMenuItem miCadTouring;
  private javax.swing.JMenuItem miMenuInicial;
  private javax.swing.JMenuItem miRelatorio;
  private javax.swing.JMenuItem miRelatorioGera;
  private javax.swing.JTable tbEsportiva;
  // End of variables declaration//GEN-END:variables
}
